dashboard:
    pattern: /
    defaults: { _controller: MinePlusMainBundle:Dashboard:index }

mineplus_main_avatar:
    pattern: /avatar/{username}/{size}.{_format}
    defaults: { _controller: MinePlusMainBundle:Image:avatar }

list:
    pattern: /players/
    defaults: { _controller: MinePlusMainBundle:Player:list }
