dashboard:
    pattern: /
    defaults: { _controller: MinePlusMainBundle:Dashboard:index }

mineplus_main_avatar:
    pattern: /avatar/{username}/{size}.{_format}
    defaults: { _controller: MinePlusMainBundle:Image:avatar }

mineplus_main_player_list:
    pattern: /players/
    defaults: { _controller: MinePlusMainBundle:Player:list }
    
mineplus_main_player_show:
    pattern: /profile/{username}
    defaults: { _controller: MinePlusMainBundle:Player:show }

mineplus_main_admin_index:
    pattern: /admin/
    defaults: { _controller: MinePlusMainBundle:Admin:index }

mineplus_main_admin_design:
    pattern: /admin/design
    defaults: { _controller: MinePlusMainBundle:Admin:design }