services:
    # Twig Extensions
    mineplus.twig.config_extension:
        class: MinePlus\MainBundle\Twig\ConfigExtension
        arguments: ['@doctrine']
        tags:
            - { name: twig.extension }
        
    mineplus.twig.avatar_extension:
        class: MinePlus\MainBundle\Twig\AvatarExtension
        arguments: ['@router']
        tags:
            - { name: twig.extension }
            
    mineplus.twig.navbar_extension:
        class: MinePlus\MainBundle\Twig\NavbarExtension
        calls:
            - [setDispatcher, ['@event_dispatcher']]
        tags:
            - { name: twig.extension }

    # Event Listeners
    mineplus.listener.navbar_listener:
        class: MinePlus\MainBundle\EventListener\NavbarListener
        tags:
            - { name: kernel.event_listener, event: navbar.build, method: onNavbarBuild }
            
    mineplus.listener.config_listener:
        class: MinePlus\MainBundle\EventListener\ConfigListener
        tags:
            - { name: kernel.event_listener, event: config.build, method: onConfigEditorBuild }
        arguments: ['@doctrine.orm.entity_manager']

    # WebSocket Topics
    mineplus.main.topic.chat:
        class: MinePlus\MainBundle\Topic\ChatTopic
        
    # Various
    mineplus.main.session.handler.doctrine:
        class: MinePlus\MainBundle\SessionStorage\DoctrineSessionHandler
        calls:
            - [setDoctrine, ['@doctrine']]