services:
    mineplus.twig.config_extension:
        class: MinePlus\MainBundle\Twig\ConfigExtension
        arguments: ['@doctrine']
        tags:
            - { name: twig.extension }
        
    mineplus.twig.avatar_extension:
        class: MinePlus\MainBundle\Twig\AvatarExtension
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    mineplus.main.topic.chat:
        class: MinePlus\MainBundle\Topic\ChatTopic
        
    mineplus.main.session.handler.doctrine:
        class: MinePlus\MainBundle\SessionStorage\DoctrineSessionHandler
        calls:
            - [setDoctrine, ['@doctrine']]