parameters:
#    mine_plus_main.example.class: MinePlus\MainBundle\Example

services:
#    mine_plus_main.example:
#        class: %mine_plus_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mineplus.twig.design_configuration_extension:
        class: MinePlus\MainBundle\Twig\DesignConfigurationExtension
        arguments: ['@kernel']
        tags:
            - { name: twig.extension }
    design_configuration:
        alias: mineplus.twig.design_configuration_extension
    mineplus.twig.avatar_extension:
        class: MinePlus\MainBundle\Twig\AvatarExtension
        arguments: ['@router']
        tags:
            - { name: twig.extension }
