parameters:
#    mine_plus_main.example.class: MinePlus\MainBundle\Example

services:
#    mine_plus_main.example:
#        class: %mine_plus_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
