services:
    # Twig Extensions
    mineplus.twig.config_extension:
        class: MinePlus\MainBundle\Twig\ConfigExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }
        
    mineplus.twig.avatar_extension:
        class: MinePlus\MainBundle\Twig\AvatarExtension
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    mineplus.twig.datetime_extension:
        class: MinePlus\MainBundle\Twig\DateTimeExtension
        tags:
            - { name: twig.extension }

    # WebSocket Topics
    mineplus.main.topic.chat:
        class: MinePlus\MainBundle\Topic\ChatTopic
        
    # Various
    mineplus.main.session.handler.doctrine:
        class: MinePlus\MainBundle\SessionStorage\DoctrineSessionHandler
        calls:
            - [setDoctrine, ['@doctrine']]
            
    # Admin
    sonata.admin.user:
        class: MinePlus\MainBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Users', label: 'Users' }
        arguments:
            - ~
            - MinePlus\MainBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [MinePlusMainBundle]]
            
    # Menu
    mineplus.main.bootstrap_renderer:
        class: MinePlus\MainBundle\Menu\BootstrapRenderer
        scope: request
        calls:
            - [ setTemplatingEngine, ['@templating']]
            - [ setCurrentMarker, ['@menu.current_marker']]
        tags:
            - { name: knp_menu.renderer, alias: bootstrap }
            
    menu.current_marker:
        class: MinePlus\MainBundle\Menu\CurrentMarker
        scope: request
        arguments: ['@request']