parameters:
#    mine_plus_minecraft.example.class: MinePlus\MinecraftBundle\Example

services:
#    mine_plus_minecraft.example:
#        class: %mine_plus_minecraft.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
