MinePlus\MainBundle\Entity\Thread:
    type: entity
    table: thread
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        createdBy:
            targetEntity: MinePlus\MainBundle\Entity\User
    oneToMany:
        messages:
            targetEntity: MinePlus\MainBundle\Entity\Message
            mappedBy: thread
        metadata:
            targetEntity: MinePlus\MainBundle\Entity\ThreadMetadata
            mappedBy: thread
            cascade: ['all']