assetic:
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../vendor/jquery/jquery/jquery-2.0.3.min.js'