security:
    encoders:
        MinePLus\MainBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_OWNER: ROLE_ADMIN

    providers:
        users:
            entity: { class: MinePlusMainBundle:User, property: username }
    firewalls:
        main:
            pattern:    ^/
            form_login: ~
            logout: ~
            anonymous: true
    access_control:
